### ISSUE TITLE
using components transport.endpoint.tls.trust_root requires to call tls.load_default_certs() to work with sslmate certificate

### ISSUE THREAD

**Issue by diefans** [crossbario/autobahn-python#1014]
We have a certificate generated with sslmate.

crosbar config:
```
---
version: 2
workers:
  - type: router
    realms:
      - name: foobar
        roles:
          - name: anonymous
            permissions:
              # allow all
              - uri: ""
                match: prefix
                allow:
                  call: true
                  register: true
                  publish: true
                  subscribe: true
                disclose:
                  caller: false
                  publisher: false
                cache: true
    transports:
      - type: websocket
        endpoint:
          type: tcp
          port: 8443
          tls:
            key: ../certs/foobar.key
            certificate: ../certs/foobar.crt
        url: wss://foobar:8443/ws
```

The autobahn component gets the following config (parsed from yaml and put straight into `**kwargs`):
```
component:
  realm: foobar
  transports:
    - type: websocket
      url: wss://foobar:8443/ws
      endpoint:
        type: tcp
        host: foobar
        port: 8443
        tls:
          hostname: foobar
          trust_root: certs/foobar.chain.crt
```

Connecting the component gives following error:
```
2018-05-29T08:56:54.330776Z [info     ] Connection failed: SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833) [autobahn.asyncio.component.Component]
```

`openssl s_client -CAfile certs/foobar.chain.crt -showcerts -connect foobar:8443` works as expected.

When I call `tls.load_default_certs()` after https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/component.py#L248 everything works.

So the question appears, is this intended and should I use a custom SSLContext for this, while I imaging it would be a good way to load default certs at least as an option, if not allways...
