### ISSUE TITLE
Authentication URL always has details passed regardless of RegisterOptions

### ISSUE THREAD

**Issue by haizaar** [crossbario/autobahn-python#1063]
Consider the following snippet:
```python
@component.register(
    "com.myapp.authenticate",
    # FIXME: details are passed by default. Why?
    # options=RegisterOptions(details_arg="details"),
)
async def authenticate(realm, authid, details):
```
`com.myapp.authenticate` is registered as authenticator in crossbar:
```yaml
  transports:
  # Main transport - requires authentication
  - type: websocket
    endpoint:
      type: tcp
      port: 8080
    auth:
      ticket:
        type: dynamic
        authenticator: com.myapp.authenticate
        authenticator-realm: auth-realm
```

`com.myapp.authenticate` is just a regular RPC, but for some reason `details` are always passed. For instance removing `details` from function signature results in:
```
TypeError: authenticate() takes 2 positional arguments but 3 were given
```
And uncommenting `RegisterOptions` results in:
```
TypeError: authenticate() got multiple values for argument 'details'
```

How come is it special?
