### ISSUE TITLE
Cannot set authrole for anonymous authentication

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#1279]
I need to connect to crossbar from a python based component, I have changed the name of the default role from `anonymous` to `testing` and changed my code accordingly, but it seems I always get `wamp.error.no_such_role:`.

Here is crossbar config
```yaml
version: 2
controller: {}
workers:
- type: router
  realms:
  - name: realm1
    roles:
    - name: testing
      permissions:
      - uri: ''
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: false
          publisher: false
        cache: true
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: 8080
```
And the following is the client code
```python
from autobahn.wamp.auth import AuthAnonymous
from autobahn.asyncio.component import Component, run
from autobahn.asyncio.wamp import Session

if __name__ == '__main__':
    comp = Component(transports="ws://localhost:8080/ws",
                     realm="realm1",
                     authentication={"anonymous": AuthAnonymous(authrole='testing')})

    @comp.on_join
    async def joined(session: Session, _details):
        print("We are connected...")


    run(comp)
```
