### ISSUE TITLE
[asyncio] No error raised using a wrong self signed TLS certificate.

### ISSUE THREAD

**Issue by rdebroiz** [crossbario/autobahn-python#1323]
TLS is in place and use a self signed certificate. With a config such has:
```
endpoint:
  type: "tcp"
  host: "host"
  port: port
  tls:
    hostname: "CA's CN"
    trust_root: "this/is/a/wrong/file" # does not exists for instance
```

The folowing code will run printing `Using default loop`.

```python
def on_connection_failed(err: Exception):
    test_conn_comp._err = err
    return True

test_conn_comp = Component(
    realm=conf["realm"],
    transports=conf["transports"],
    authentication=conf["authentication"],
    is_fatal=on_connection_failed
)

@test_conn_comp.on_join
def on_joined(*args, **kwargs):
    print("Connection established.")
    test_conn_comp.stop()

test_conn_comp._err = None
test_conn_comp.start()
if test_conn_comp._err:
    raise RuntimeError(f"Connection refused. reason {test_conn_comp._err.error_message()}")
```

Expected: An error to be raised such as `FileNotExistsError`, `SSLError`, etc.
