### ISSUE TITLE
CI: auto-generate list of published Docker image references

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1516]
After building and uploading new Docker images for Autobahn, it would be great to have the new Docker images listed in a way that allows exact reference and direct use in other projects

Docker CLI and docker-compose  allows to read env vars from a `.env` file, that if present, will make env vars already available during "docker-compose" phase (not only inside containers)

```
# Docker image references for Autobahn v21.1.1 (20220128-dc626948)
# https://hub.docker.com/r/crossbario/autobahn-python/tags?page=1&name=22.1.1

DOCKER_IMAGE_AUTOBAHN_PYTHON=crossbario/autobahn-python@sha256:dfed71b8441e219f2746ff08398d1571e99c666bf85bb4136fe2f9bf1a568650
```

Above can be computed like this

```
echo ${AUTOBAHN_VERSION}
echo ${AUTOBAHN_BUILD_ID}

docker inspect --format='{{index .RepoDigests 0}}' crossbario/autobahn-python:cpy-amd64-${AUTOBAHN_VERSION}-${AUTOBAHN_BUILD_ID}
```

**Comment by oberstet** [comment]
So say you have 2 env files

* `.env`
* `myapp.env`

Then you can use a `docker-compose.yml` like

```
    myapp:
        container_name: myapp
        image: ${DOCKER_IMAGE_AUTOBAHN_PYTHON}
        env_file:
            - myapp.env
        user: ${UID}:${GID}
        tty: true
        volumes:
            - "/home/ubuntu/myapp/:/app:rw"
        command:
            - python
            - myapp.py
```

The crucial point is: `DOCKER_IMAGE_AUTOBAHN_PYTHON`, `UID` and `GID` must be defined in `.env`. stuff in `myapp.env` is only available _within `myapp.py`!
